praxisregister_src/apps/practices/urls.py
from django.urls import path

from accreditation.views import PracticeAccreditationCreate, PracticeAccreditationList
from contactnotes.views import ContactNoteCreate, PracticeContactNotes
from documents.views import DocumentCreate, PracticeDocuments
from events.views.participation_views import EventParticipationCreate, PracticeEventParticipationList
from persons.views import PersonsInPractice, PersonAdd
from processes.views import PracticeProcessList, ProcessParticipationCreate, process_step_select_option
from studies.views.practice_study_overview import PracticeStudyParticipations, StudyParticipationCreate
from todos.views import PracticeToDoCreate, PracticeToDoList, ToDoDelete
from .views.allowed_institutes import AllowedInstitutes, AllowedInstitutesEdit
from .views.practice_base_data import PracticeDetail, PracticeOpeningHoursEdit, \
    PracticeContactEdit, UpdatePracticeBaseData
from .views.contract import *
from .views.it_infrastructure import PracticeITDetail, PracticeITSystemHouseEdit, PracticeITOtherEdit, \
    PracticeITPDMSEdit, PracticeITNotepadEdit
from .views.notepad import PracticeNotepadEdit
from .views.practice import PracticeCreate, Practices, practice_table
from .views.sites import AdditionalSiteEdit, AdditionalSiteDelete, AdditionalSiteCreateView
from .views.practice_structure import *
from .views.research_tandem import TandemAssistantDetail, TandemDoctorDetail
from practices.views.practice_communication import *

app_name = 'practices'

practice_urls = [
    path('', Practices.as_view(), name='list'),
    path('htmx/practice-table/', practice_table, name='practice_table'),
    path('htmx/process-step-selection/', process_step_select_option, name='process-step-selection'),
    path('<int:pk>/', PracticeDetail.as_view(), name='detail'),
    path('new', PracticeCreate.as_view(), name='create'),
    path('<int:pk>/sites/new', AdditionalSiteCreateView.as_view(), name='create-site'),
    path('sites/<int:pk>/edit', AdditionalSiteEdit.as_view(), name='edit-site'),
    path('sites/<int:pk>/delete', AdditionalSiteDelete.as_view(), name='delete-site'),
    path('<int:pk>/notepad/', PracticeNotepadEdit.as_view(), name='edit-notepad'),
    path('<int:pk>/information/edit', UpdatePracticeBaseData.as_view(), name='edit-info'),
    path('<int:pk>/opening-hours/edit', PracticeOpeningHoursEdit.as_view(), name='edit-opening-hours'),
    path('<int:pk>/contact/edit', PracticeContactEdit.as_view(), name='edit-contact'),
]

todo_urls = [
    path('<int:pk>/todos/', PracticeToDoList.as_view(), name='todo-list'),
    path('<int:pk>/todos/new', PracticeToDoCreate.as_view(), name='create-todo'),
    path('<int:pk>/todos/delete', ToDoDelete.as_view(), name='todo-delete'),
]

accreditation_urls = [
    path('<int:pk>/accreditations/new', PracticeAccreditationCreate.as_view(), name='accreditation-add'),
    path('<int:pk>/accreditations/', PracticeAccreditationList.as_view(), name='accreditations'),
]

study_urls = [
    path('<int:pk>/study-participations/', PracticeStudyParticipations.as_view(),
         name='study-participation-list'),
    path('<int:pk>/study-participations/new', StudyParticipationCreate.as_view(),
         name='study-participation-create'),
]

event_urls = [
    path('<int:pk>/event-participations/', PracticeEventParticipationList.as_view(),
         name='event-participation-list'),
    path('<int:pk>/event-participations/new', EventParticipationCreate.as_view(),
         name='event-participation-create'),
]

process_urls = [
    path('<int:pk>/process-participations/', PracticeProcessList.as_view(), name='process-list'),
    path('<int:pk>/process-participations/new', ProcessParticipationCreate.as_view(),
         name='process-participation-create'),
]

contact_notes_urls = [
    path('<int:pk>/contact-notes/', PracticeContactNotes.as_view(), name='contactnote-list'),
    path('<int:pk>/contact-notes/new', ContactNoteCreate.as_view(), name='contactnote-create'),
]

documents_urls = [
    path('<int:pk>/documents/', PracticeDocuments.as_view(), name='document-list'),
    path('<int:pk>/documents/new', DocumentCreate.as_view(), name='document-create'),
]

structure_urls = [
    path('<int:pk>/structure/', PracticeStructureDetail.as_view(),
         name='structure-detail'),
    path('<int:pk>/structure/doctors/edit', PracticeStructureDoctorsEdit.as_view(),
         name='structure-doctors-edit'),
    path('<int:pk>/structure/staff/edit', PracticeStructureStaffEdit.as_view(),
         name='structure-staff-edit'),
    path('structure/assistant-qualifications/<int:pk>/delete',
         PracticeAssistantsAdditionalQualificationDelete.as_view(),
         name='structure-assistant-qualifications-delete'),
    path('<int:pk>/structure/services/edit', PracticeStructureServicesEdit.as_view(),
         name='structure-services-edit'),
    path('structure/engagements/<int:pk>/delete', PracticeEngagementDelete.as_view(),
         name='structure-engagement-delete'),
    path('<int:pk>/structure/general/edit', PracticeStructureGeneralEdit.as_view(),
         name='structure-general-edit'),
    path('structure/dmp-entries/<int:pk>/edit', DiseaseManagementProgramEntryEdit.as_view(),
         name='dmp-entry-edit'),
    path('structure/offers-service/<int:pk>/delete', ServicesPracticeOffersDelete.as_view(), name='practice-offers-delete'),
    path('<int:pk>/structure/treatment-by-age/edit', PracticeTreatmentByAgeGroupPerQuarterEdit.as_view(), name='structure-treatment-by-age-edit'),
    path('structure/treatment-by-age/<int:pk>/delete', PracticeTreatmentByAgeGroupPerQuarterDelete.as_view(), name='structure-treatment-by-age-delete'),
]

it_urls = [
    path('<int:pk>/it/', PracticeITDetail.as_view(), name='it-detail'),
    path('<int:pk>/it/system-house/edit', PracticeITSystemHouseEdit.as_view(), name='it-system-house-edit'),
    path('<int:pk>/it/pdms/edit', PracticeITPDMSEdit.as_view(), name='it-pdms-edit'),
    path('<int:pk>/it/other/edit', PracticeITOtherEdit.as_view(), name='it-other-edit'),
    path('<int:pk>/it/notepad/edit', PracticeITNotepadEdit.as_view(), name='it-notepad-edit'),
]

communication_urls = [
    path('<int:pk>/communication/', PracticeCommunicationView.as_view(), name='communication-detail'),
    path('<int:pk>/communication/spoken-language/edit', PracticeCommunicationEdit.as_view(), name='communication-spoken-language-edit'),
    path('communication/spoken-language/<int:pk>/delete', CommunicationSpokenLanguageDelete.as_view(), name='communication-spoken-language-delete'),
    path('communication/spoken-language/<int:pk>/percentage', CommunicationSpokenLanguagePercentage.as_view(), name='communication-spoken-language-percentage'),
    path('communication/interpreter/<int:pk>/delete', CommunicationInterpreterDelete.as_view(), name='communication-interpreter-delete'),
    path('communication/interpreter/<int:pk>/amount', CommunicationInterpreterAmount.as_view(), name='communication-interpreter-amount'),

    path('<int:pk>/communication/colleagues', PracticeDigitalCommunicationWithColleaguesEdit.as_view(), name='communication-digital-colleagues-edit'),
    path('communication/colleagues/<int:pk>/delete', CommunicationWithColleaguesDelete.as_view(), name='communication-digital-colleagues-delete'),
    
    path('<int:pk>/communication/patients', PracticeDigitalCommunicationWithPatientsEdit.as_view(), name='communication-digital-patients-edit'),
    path('communication/patients/<int:pk>/delete', CommunicationWithPatientsDelete.as_view(), name='communication-digital-patients-delete'),
]

contract_urls = [
    path('<int:pk>/contract/download', download_contract_file, name='contract-download'),
    path('<int:pk>/contract/delete', delete_contract_file, name='contract-delete'),
    path('<int:pk>/contract/edit', ContractEdit.as_view(), name='contract-edit'),
]

persons_urls = [
    path('<int:pk>/persons/', PersonsInPractice.as_view(), name='persons'),
    path('<int:pk>/persons/new', PersonAdd.as_view(), name='person-add'),
]

research_tandem_urls = [
    path('<int:pk>/research-tandem/doctor/', TandemDoctorDetail.as_view(), name='tandem-doctor-detail'),
    path('<int:pk>/research-tandem/assistant/', TandemAssistantDetail.as_view(), name='tandem-assistant-detail'),
]

allowed_institutes_urls = [
    path('<int:pk>/allowed-institutes/', AllowedInstitutes.as_view(), name="allowed-institutes"),
    path('<int:pk>/allowed-institutes/add', AllowedInstitutesEdit.as_view(), name="allowed-institutes-edit")
]

urlpatterns = []
urlpatterns.extend(practice_urls)
urlpatterns.extend(persons_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(it_urls)
urlpatterns.extend(communication_urls)
urlpatterns.extend(structure_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(contact_notes_urls)
urlpatterns.extend(documents_urls)
urlpatterns.extend(event_urls)
urlpatterns.extend(process_urls)
urlpatterns.extend(study_urls)
urlpatterns.extend(todo_urls)
urlpatterns.extend(accreditation_urls)
urlpatterns.extend(research_tandem_urls)
urlpatterns.extend(allowed_institutes_urls)

praxisregister_src/apps/processes/urls.py
from django.urls import path
from processes import views

app_name = 'processes'
urlpatterns = [
    
     # Process definitions
     path('definitions/', views.ProcessDefinitions.as_view(), name='definition-list'),
     path('definitions/<int:pk>/copy', views.CreateProcessDefinitionCopy.as_view(), name='definition-copy'),
     path('definitions/new', views.ProcessDefinitionCreate.as_view(), name='definition-create'),
     path('definitions/<int:pk>/', views.ProcessDefinitionDetail.as_view(), name='definition-detail'),  
     path('definitions/<int:pk>/update', views.ProcessDefinitionUpdate.as_view(), name='definition-update'),
     path('definitions/<int:pk>/delete', views.ProcessDefinitionDelete.as_view(), name='definition-delete'),
     path('definitions/<int:pk>/instantiate', views.bulk_create_processes, name='definition-instantiate'),
     path('definitions/<int:pk>/finalize', views.ProcessDefinitionFinalize.as_view(), name='definition-finalize'),

     # Process instances
     path('definitions/<int:pk>/instances', views.ProcessInstances.as_view(), name='process-instances'),
     path('instances/<int:pk>/delete', views.ProcessDelete.as_view(), name='process-delete'),
     path('instances/<int:pk>/edit-deadline', views.ProcessDeadlineEdit.as_view(), name='process-edit-deadline'),

     # Step definitions
     path('definitions/<int:pk>/steps/new', views.StepDefinitionCreate.as_view(), name='step-definition-add'),
     path('definitions/<int:pk>/steps/detail', views.StepDefinitionDetail.as_view(), name='step-definition-detail'),
     path('steps/definitions/<int:pk>/update', views.StepDefinitionUpdate.as_view(), name='step-definition-update'),
     path('steps/definitions/<int:pk>/delete', views.StepDefinitionDelete.as_view(), name='step-definition-delete'),
     path('steps/definitions/<int:pk>/move_up', views.StepDefinitionMoveUp.as_view(), name='step-definition-move-up'),
     path('steps/definitions/<int:pk>/move_down', views.StepDefinitionMoveDown.as_view(), name='step-definition-move-down'),

     # Step instances
     path('steps/instances/<int:pk>/mark_as_done', views.StepMarkAsDone.as_view(), name='step-mark-as-done'),
     path('steps/instances/<int:pk>/reset', views.StepReset.as_view(), name='step-reset'),
     path('steps/instances/<int:pk>/edit-date', views.StepDateEdit.as_view(), name='step-edit-date'),
]

praxisregister_src/apps/schedule/urls.py
from django.urls import re_path
from django.views.generic.list import ListView

from schedule.feeds import CalendarICalendar, UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView,
    CalendarView,
    CancelOccurrenceView,
    CreateEventView,
    CreateOccurrenceView,
    DeleteEventView,
    EditEventView,
    EditOccurrenceView,
    EventView,
    FullCalendarView,
    OccurrencePreview,
    OccurrenceView,
    api_move_or_resize_by_code,
    api_occurrences,
    api_select_create,
)

urlpatterns = [
    re_path(r"^$", ListView.as_view(model=Calendar), name="calendar_list"),
    re_path(
        r"^calendar/year/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_year.html"),
        name="year_calendar",
        kwargs={"period": Year},
    ),
    re_path(
        r"^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_tri_month.html"),
        name="tri_month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(
            template_name="schedule/calendar_compact_month.html"
        ),
        name="compact_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_month.html"),
        name="month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/week/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_week.html"),
        name="week_calendar",
        kwargs={"period": Week},
    ),
    re_path(
        r"^calendar/daily/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_day.html"),
        name="day_calendar",
        kwargs={"period": Day},
    ),
    re_path(
        r"^calendar/(?P<calendar_slug>[-\w]+)/$",
        CalendarView.as_view(),
        name="calendar_home",
    ),
    re_path(
        r"^fullcalendar/(?P<calendar_slug>[-\w]+)/$",
        FullCalendarView.as_view(),
        name="fullcalendar",
    ),
    # Event Urls
    re_path(
        r"^event/create/(?P<calendar_slug>[-\w]+)/$",
        CreateEventView.as_view(),
        name="calendar_create_event",
    ),
    re_path(
        r"^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$",
        EditEventView.as_view(),
        name="edit_event",
    ),
    re_path(r"^event/(?P<event_id>\d+)/$", EventView.as_view(), name="event"),
    re_path(
        r"^event/delete/(?P<event_id>\d+)/$",
        DeleteEventView.as_view(),
        name="delete_event",
    ),
    # urls for already persisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        OccurrenceView.as_view(),
        name="occurrence",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        EditOccurrenceView.as_view(),
        name="edit_occurrence",
    ),
    # urls for unpersisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        OccurrencePreview.as_view(),
        name="occurrence_by_date",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence_by_date",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CreateOccurrenceView.as_view(),
        name="edit_occurrence_by_date",
    ),
    # feed urls
    re_path(
        r"^feed/calendar/upcoming/(?P<calendar_id>\d+)/$",
        UpcomingEventsFeed(),
        name="upcoming_events_feed",
    ),
    re_path(r"^ical/calendar/(.*)/$", CalendarICalendar(), name="calendar_ical"),
    # api urls
    re_path(r"^api/occurrences", api_occurrences, name="api_occurrences"),
    re_path(
        r"^api/move_or_resize/$", api_move_or_resize_by_code, name="api_move_or_resize"
    ),
    re_path(r"^api/select_create/$", api_select_create, name="api_select_create"),
    re_path(r"^$", ListView.as_view(queryset=Calendar.objects.all()), name="schedule"),
]

praxisregister_src/config/urls.py
from django.urls import path, include
from rest_framework import routers

from practices.views.practice import Practices, PracticeViewSet
from persons.views import PersonViewSet
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from utils.ckeditor5 import upload_file

api_router = routers.DefaultRouter()
api_router.register(r'practices', PracticeViewSet, basename='practices')
api_router.register(r'persons', PersonViewSet, basename='persons')

# Admin stuff
admin.site.site_header = "Praxisregister Admin"
admin.site.site_title = "Praxisregister Admin Portal"

urlpatterns = [
    path('', Practices.as_view(), name='landing-page'),  # TODO: Maybe use a redirect to Practice list view here.
    path('taggit/', include('taggit_selectize.urls')),
    path('headquarters/', admin.site.urls),
    path('users/', include('users.urls')),
    path('institutes/', include('institutes.urls')),
    path('practices/', include('practices.urls')),
    path('accreditations/', include('accreditation.urls')),
    path('studies/', include('studies.urls')),
    path('events/', include('events.urls')),
    path('todos/', include('todos.urls')),
    path('contactnotes/', include('contactnotes.urls')),
    path('documents/', include('documents.urls')),
    path('processes/', include('processes.urls')),
    path('persons/', include('persons.urls')),
    path('exporter/', include('exporter.urls')),
    path('changelogs/', include('changelogs.urls')),
    path('mail/', include('mail.urls')),
    path('importer/', include('importer.urls')),
    path('practice_importer/', include('practice_importer.urls')),
    path('kbv_importer/', include('kbv_importer.urls')),
    path('feedback/', include('feedback.urls')),
    path('schedule/', include('schedule.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ck_editor_5_upload_file"), #Using own implementation of image upload
    path('api/', include(api_router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

praxisregister_src/templates/practices/processes/process_list.html
{% extends 'practices/practice_base.html' %}
{% load i18n %}
{% load crispy_forms_filters %}

{% block practice-content %}
<h3 class="display-6">
    {% trans 'Processes' %}
    <a href="{% url 'practices:process-participation-create' practice.id %}">
        <i class="fa fa-plus-circle"></i>
    </a>
</h3>
{% for process in object_list %}

<table class="table table-sm table-borderless">
    <tbody>
        <tr class="table-primary">
            <td class="px-2">
                <span>
                    {% if process.is_due %}
                    <i class="fa-solid fa-circle-exclamation text-danger"></i>
                    {% endif %}

                    {% trans 'Instance' %} #{{ process.id }}: 
                    <strong>{{ process.process_definition.name }}</strong>
                    {% if process.deadline %}
                    ({% trans "Deadline" %}: {{ process.deadline }})
                    {% endif %}
                </span>
                <span class="float-end">
                    {% trans 'Created at' %} {{ process.created_at }} {% trans 'by' %} {{ process.created_by }}
                </span>
            </td>
        </tr>
        <tr>
            <td>
                <div class="row">
                    <div class="col-sm">
                        <span class="float-end">
                            <a href="{% url 'processes:process-edit-deadline' process.id %}"
                                class="btn btn-sm btn-outline-primary">
                                <i class="fas fa-edit"></i> 
                                {% if process.deadline %}
                                {% trans "Edit deadline" %}
                                {% else %}
                                {% trans "Set deadline" %}
                                {% endif %}
                            </a>
                            <a href="{% url 'processes:process-instances' process.process_definition.id %}"
                                class="btn btn-sm btn-outline-primary">
                                <i class="fas fa-info-circle"></i> {% trans 'Process Details' %}
                            </a>
                            <a href="{% url 'processes:process-delete' process.id %}"
                                class="btn btn-sm btn-outline-danger">
                                <i class="fa fa-trash"></i> {% trans 'Delete Instance' %}
                            </a>
                        </span>
                        <button class="btn btn-sm btn-outline-primary" role="button" data-bs-toggle="collapse"
                            href="#toogle-{{ process.id }}" aria-expanded="false"
                            aria-controls="toogle-{{ process.id }}">{% trans 'Show/Hide steps' %}
                        </button>
                        <div class="collapse content" id="toogle-{{ process.id }}">
                            {% include 'practices/processes/process_step_table.html' %}
                        </div>
                    </div>

                </div>
            </td>
        </tr>
    </tbody>
</table>
{% endfor %}

{% include 'global/snippets/pagination.html' %}

{% endblock %}

{% block side_bar_right %}
<ul class="nav flex-column w-100">
</ul>
{% endblock %}

praxisregister_src/templates/practices/processes/process_step_options.html
{% load i18n %}

<div class="row ">
    <div class="col-md ">
        <div id="div_id_process__step__step_definition__name" class="mb-3">
            <label for="id_process__step__step_definition__name" class="form-label">
                {% trans 'Process step fullfilled' %}
            </label>
            <select name="process__step__step_definition__name" class="select form-select"
                id="id_process__step__step_definition__name">
                <option value="" selected="">---------</option>
                {% for step_definition in step_definitions %}
                <option value={{step_definition.pk}}>{{ step_definition.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md ">
        <div id="div_id_processStep_not_fullfilled" class="mb-3">
            <label for="id_processStep_not_fullfilled" class="form-label">
                {% trans 'Process step not fullfilled' %}
            </label>
            <select name="processStep_not_fullfilled" class="select form-select" id="id_processStep_not_fullfilled">
                <option value="" selected="">---------</option>
                {% for step_definition in step_definitions %}
                <option value={{step_definition.pk}}>{{ step_definition.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
</div>

praxisregister_src/templates/practices/processes/process_step_table.html
{% load i18n %}
{% load safe_urlize %}

<div id="entry-{{ process.id }}">
    <table class="table table-sm">
        <thead>
            <tr>
                <th style="width: 5%">{% trans 'Step #' %}</th>
                <th style="width: 15%">{% trans 'Name' %}</th>
                <th style="width: 25%">{% trans 'Description' %}</th>
                <th style="width: 5%">{% trans 'Done' %}</th>
                <th style="width: 8%">{% trans 'at' %}</th>
                <th style="width: 8%">{% trans 'by' %}</th>
                <th style="width: 5%"></th>
            </tr>
        </thead>
        <tbody>
            {% for step in process.steps %}
            <tr>
                <td>{{ step.step_definition.position_index }}</td>
                <td>{{ step.step_definition.name }}</td>
                <td>
                {% if step.step_definition.description|length < 255 %}
                    {{ step.step_definition.description|safe_urlize }}
                {% else %}
                    {% url 'processes:step-definition-detail' step.step_definition.id as detail_url %}
                    <a href="{{detail_url}}" class="btn btn-outline-primary btn-sm"><i class="fa fa-eye"></i></a>
                {% endif %}
                </td>
                <td>
                    {% if step.is_done %}
                    <i class="fa fa-check-circle text-success"></i>
                    {% else %}
                    <i class="fa fa-times-circle text-danger"></i>
                    {% endif %}
                </td>
                <td>
                    {% if step.is_done %}
                    {{ step.done_at|date:"SHORT_DATE_FORMAT" }}
                    <a href="{% url 'processes:step-edit-date' step.id %}">
                        <i class="fa fa-edit"></i>
                    </a>
                    {% else %}
                    -
                    {% endif %}
                </td>
                <td>
                    {% if step.is_done and step.done_by %}
                    {{ step.done_by.full_name }}
                    {% else %}
                    -
                    {% endif %}
                </td>
                <td>
                    <span class="float-end">
                        {% if step.is_done %}
                        {% include 'processes/buttons/step_reset.html' %}
                        {% else %}
                        {% include 'processes/buttons/step_mark_as_done.html' %}
                        {% endif %}
                    </span>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% block custom_script %}
{% include "global/snippets/htmx_post_script.html" %}
{% endblock %}