praxisregister_src/apps/accreditation/urls.py
from django.urls import path

from . import views

app_name = 'accreditations'
urlpatterns = [
    path('<int:pk>/', views.AccreditationDetailChecklist.as_view(), name='detail'),
    path('<int:pk>/edit-checklist', views.AccreditationDetailChecklistEdit.as_view(), name='edit-checklist'),
    path('<int:pk>/delete', views.AccreditationDelete.as_view(), name='delete'),
    path('<int:pk>/edit', views.AccreditationStatusEdit.as_view(), name='edit'),
    path('<int:pk>/date/edit', views.AccreditationDateEdit.as_view(), name='edit-accredited-at'),
]

praxisregister_src/apps/practices/urls.py
from django.urls import path

from accreditation.views import PracticeAccreditationCreate, PracticeAccreditationList
from contactnotes.views import ContactNoteCreate, PracticeContactNotes
from documents.views import DocumentCreate, PracticeDocuments
from events.views.participation_views import EventParticipationCreate, PracticeEventParticipationList
from persons.views import PersonsInPractice, PersonAdd
from processes.views import PracticeProcessList, ProcessParticipationCreate, process_step_select_option
from studies.views.practice_study_overview import PracticeStudyParticipations, StudyParticipationCreate
from todos.views import PracticeToDoCreate, PracticeToDoList, ToDoDelete
from .views.allowed_institutes import AllowedInstitutes, AllowedInstitutesEdit
from .views.practice_base_data import PracticeDetail, PracticeOpeningHoursEdit, \
    PracticeContactEdit, UpdatePracticeBaseData
from .views.contract import *
from .views.it_infrastructure import PracticeITDetail, PracticeITSystemHouseEdit, PracticeITOtherEdit, \
    PracticeITPDMSEdit, PracticeITNotepadEdit
from .views.notepad import PracticeNotepadEdit
from .views.practice import PracticeCreate, Practices, practice_table
from .views.sites import AdditionalSiteEdit, AdditionalSiteDelete, AdditionalSiteCreateView
from .views.practice_structure import *
from .views.research_tandem import TandemAssistantDetail, TandemDoctorDetail
from practices.views.practice_communication import *

app_name = 'practices'

practice_urls = [
    path('', Practices.as_view(), name='list'),
    path('htmx/practice-table/', practice_table, name='practice_table'),
    path('htmx/process-step-selection/', process_step_select_option, name='process-step-selection'),
    path('<int:pk>/', PracticeDetail.as_view(), name='detail'),
    path('new', PracticeCreate.as_view(), name='create'),
    path('<int:pk>/sites/new', AdditionalSiteCreateView.as_view(), name='create-site'),
    path('sites/<int:pk>/edit', AdditionalSiteEdit.as_view(), name='edit-site'),
    path('sites/<int:pk>/delete', AdditionalSiteDelete.as_view(), name='delete-site'),
    path('<int:pk>/notepad/', PracticeNotepadEdit.as_view(), name='edit-notepad'),
    path('<int:pk>/information/edit', UpdatePracticeBaseData.as_view(), name='edit-info'),
    path('<int:pk>/opening-hours/edit', PracticeOpeningHoursEdit.as_view(), name='edit-opening-hours'),
    path('<int:pk>/contact/edit', PracticeContactEdit.as_view(), name='edit-contact'),
]

todo_urls = [
    path('<int:pk>/todos/', PracticeToDoList.as_view(), name='todo-list'),
    path('<int:pk>/todos/new', PracticeToDoCreate.as_view(), name='create-todo'),
    path('<int:pk>/todos/delete', ToDoDelete.as_view(), name='todo-delete'),
]

accreditation_urls = [
    path('<int:pk>/accreditations/new', PracticeAccreditationCreate.as_view(), name='accreditation-add'),
    path('<int:pk>/accreditations/', PracticeAccreditationList.as_view(), name='accreditations'),
]

study_urls = [
    path('<int:pk>/study-participations/', PracticeStudyParticipations.as_view(),
         name='study-participation-list'),
    path('<int:pk>/study-participations/new', StudyParticipationCreate.as_view(),
         name='study-participation-create'),
]

event_urls = [
    path('<int:pk>/event-participations/', PracticeEventParticipationList.as_view(),
         name='event-participation-list'),
    path('<int:pk>/event-participations/new', EventParticipationCreate.as_view(),
         name='event-participation-create'),
]

process_urls = [
    path('<int:pk>/process-participations/', PracticeProcessList.as_view(), name='process-list'),
    path('<int:pk>/process-participations/new', ProcessParticipationCreate.as_view(),
         name='process-participation-create'),
]

contact_notes_urls = [
    path('<int:pk>/contact-notes/', PracticeContactNotes.as_view(), name='contactnote-list'),
    path('<int:pk>/contact-notes/new', ContactNoteCreate.as_view(), name='contactnote-create'),
]

documents_urls = [
    path('<int:pk>/documents/', PracticeDocuments.as_view(), name='document-list'),
    path('<int:pk>/documents/new', DocumentCreate.as_view(), name='document-create'),
]

structure_urls = [
    path('<int:pk>/structure/', PracticeStructureDetail.as_view(),
         name='structure-detail'),
    path('<int:pk>/structure/doctors/edit', PracticeStructureDoctorsEdit.as_view(),
         name='structure-doctors-edit'),
    path('<int:pk>/structure/staff/edit', PracticeStructureStaffEdit.as_view(),
         name='structure-staff-edit'),
    path('structure/assistant-qualifications/<int:pk>/delete',
         PracticeAssistantsAdditionalQualificationDelete.as_view(),
         name='structure-assistant-qualifications-delete'),
    path('<int:pk>/structure/services/edit', PracticeStructureServicesEdit.as_view(),
         name='structure-services-edit'),
    path('structure/engagements/<int:pk>/delete', PracticeEngagementDelete.as_view(),
         name='structure-engagement-delete'),
    path('<int:pk>/structure/general/edit', PracticeStructureGeneralEdit.as_view(),
         name='structure-general-edit'),
    path('structure/dmp-entries/<int:pk>/edit', DiseaseManagementProgramEntryEdit.as_view(),
         name='dmp-entry-edit'),
    path('structure/offers-service/<int:pk>/delete', ServicesPracticeOffersDelete.as_view(), name='practice-offers-delete'),
    path('<int:pk>/structure/treatment-by-age/edit', PracticeTreatmentByAgeGroupPerQuarterEdit.as_view(), name='structure-treatment-by-age-edit'),
    path('structure/treatment-by-age/<int:pk>/delete', PracticeTreatmentByAgeGroupPerQuarterDelete.as_view(), name='structure-treatment-by-age-delete'),
]

it_urls = [
    path('<int:pk>/it/', PracticeITDetail.as_view(), name='it-detail'),
    path('<int:pk>/it/system-house/edit', PracticeITSystemHouseEdit.as_view(), name='it-system-house-edit'),
    path('<int:pk>/it/pdms/edit', PracticeITPDMSEdit.as_view(), name='it-pdms-edit'),
    path('<int:pk>/it/other/edit', PracticeITOtherEdit.as_view(), name='it-other-edit'),
    path('<int:pk>/it/notepad/edit', PracticeITNotepadEdit.as_view(), name='it-notepad-edit'),
]

communication_urls = [
    path('<int:pk>/communication/', PracticeCommunicationView.as_view(), name='communication-detail'),
    path('<int:pk>/communication/spoken-language/edit', PracticeCommunicationEdit.as_view(), name='communication-spoken-language-edit'),
    path('communication/spoken-language/<int:pk>/delete', CommunicationSpokenLanguageDelete.as_view(), name='communication-spoken-language-delete'),
    path('communication/spoken-language/<int:pk>/percentage', CommunicationSpokenLanguagePercentage.as_view(), name='communication-spoken-language-percentage'),
    path('communication/interpreter/<int:pk>/delete', CommunicationInterpreterDelete.as_view(), name='communication-interpreter-delete'),
    path('communication/interpreter/<int:pk>/amount', CommunicationInterpreterAmount.as_view(), name='communication-interpreter-amount'),

    path('<int:pk>/communication/colleagues', PracticeDigitalCommunicationWithColleaguesEdit.as_view(), name='communication-digital-colleagues-edit'),
    path('communication/colleagues/<int:pk>/delete', CommunicationWithColleaguesDelete.as_view(), name='communication-digital-colleagues-delete'),
    
    path('<int:pk>/communication/patients', PracticeDigitalCommunicationWithPatientsEdit.as_view(), name='communication-digital-patients-edit'),
    path('communication/patients/<int:pk>/delete', CommunicationWithPatientsDelete.as_view(), name='communication-digital-patients-delete'),
]

contract_urls = [
    path('<int:pk>/contract/download', download_contract_file, name='contract-download'),
    path('<int:pk>/contract/delete', delete_contract_file, name='contract-delete'),
    path('<int:pk>/contract/edit', ContractEdit.as_view(), name='contract-edit'),
]

persons_urls = [
    path('<int:pk>/persons/', PersonsInPractice.as_view(), name='persons'),
    path('<int:pk>/persons/new', PersonAdd.as_view(), name='person-add'),
]

research_tandem_urls = [
    path('<int:pk>/research-tandem/doctor/', TandemDoctorDetail.as_view(), name='tandem-doctor-detail'),
    path('<int:pk>/research-tandem/assistant/', TandemAssistantDetail.as_view(), name='tandem-assistant-detail'),
]

allowed_institutes_urls = [
    path('<int:pk>/allowed-institutes/', AllowedInstitutes.as_view(), name="allowed-institutes"),
    path('<int:pk>/allowed-institutes/add', AllowedInstitutesEdit.as_view(), name="allowed-institutes-edit")
]

urlpatterns = []
urlpatterns.extend(practice_urls)
urlpatterns.extend(persons_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(it_urls)
urlpatterns.extend(communication_urls)
urlpatterns.extend(structure_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(contact_notes_urls)
urlpatterns.extend(documents_urls)
urlpatterns.extend(event_urls)
urlpatterns.extend(process_urls)
urlpatterns.extend(study_urls)
urlpatterns.extend(todo_urls)
urlpatterns.extend(accreditation_urls)
urlpatterns.extend(research_tandem_urls)
urlpatterns.extend(allowed_institutes_urls)

praxisregister_src/apps/schedule/urls.py
from django.urls import re_path
from django.views.generic.list import ListView

from schedule.feeds import CalendarICalendar, UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView,
    CalendarView,
    CancelOccurrenceView,
    CreateEventView,
    CreateOccurrenceView,
    DeleteEventView,
    EditEventView,
    EditOccurrenceView,
    EventView,
    FullCalendarView,
    OccurrencePreview,
    OccurrenceView,
    api_move_or_resize_by_code,
    api_occurrences,
    api_select_create,
)

urlpatterns = [
    re_path(r"^$", ListView.as_view(model=Calendar), name="calendar_list"),
    re_path(
        r"^calendar/year/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_year.html"),
        name="year_calendar",
        kwargs={"period": Year},
    ),
    re_path(
        r"^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_tri_month.html"),
        name="tri_month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(
            template_name="schedule/calendar_compact_month.html"
        ),
        name="compact_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_month.html"),
        name="month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/week/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_week.html"),
        name="week_calendar",
        kwargs={"period": Week},
    ),
    re_path(
        r"^calendar/daily/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_day.html"),
        name="day_calendar",
        kwargs={"period": Day},
    ),
    re_path(
        r"^calendar/(?P<calendar_slug>[-\w]+)/$",
        CalendarView.as_view(),
        name="calendar_home",
    ),
    re_path(
        r"^fullcalendar/(?P<calendar_slug>[-\w]+)/$",
        FullCalendarView.as_view(),
        name="fullcalendar",
    ),
    # Event Urls
    re_path(
        r"^event/create/(?P<calendar_slug>[-\w]+)/$",
        CreateEventView.as_view(),
        name="calendar_create_event",
    ),
    re_path(
        r"^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$",
        EditEventView.as_view(),
        name="edit_event",
    ),
    re_path(r"^event/(?P<event_id>\d+)/$", EventView.as_view(), name="event"),
    re_path(
        r"^event/delete/(?P<event_id>\d+)/$",
        DeleteEventView.as_view(),
        name="delete_event",
    ),
    # urls for already persisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        OccurrenceView.as_view(),
        name="occurrence",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        EditOccurrenceView.as_view(),
        name="edit_occurrence",
    ),
    # urls for unpersisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        OccurrencePreview.as_view(),
        name="occurrence_by_date",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence_by_date",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CreateOccurrenceView.as_view(),
        name="edit_occurrence_by_date",
    ),
    # feed urls
    re_path(
        r"^feed/calendar/upcoming/(?P<calendar_id>\d+)/$",
        UpcomingEventsFeed(),
        name="upcoming_events_feed",
    ),
    re_path(r"^ical/calendar/(.*)/$", CalendarICalendar(), name="calendar_ical"),
    # api urls
    re_path(r"^api/occurrences", api_occurrences, name="api_occurrences"),
    re_path(
        r"^api/move_or_resize/$", api_move_or_resize_by_code, name="api_move_or_resize"
    ),
    re_path(r"^api/select_create/$", api_select_create, name="api_select_create"),
    re_path(r"^$", ListView.as_view(queryset=Calendar.objects.all()), name="schedule"),
]

praxisregister_src/config/urls.py
from django.urls import path, include
from rest_framework import routers

from practices.views.practice import Practices, PracticeViewSet
from persons.views import PersonViewSet
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from utils.ckeditor5 import upload_file

api_router = routers.DefaultRouter()
api_router.register(r'practices', PracticeViewSet, basename='practices')
api_router.register(r'persons', PersonViewSet, basename='persons')

# Admin stuff
admin.site.site_header = "Praxisregister Admin"
admin.site.site_title = "Praxisregister Admin Portal"

urlpatterns = [
    path('', Practices.as_view(), name='landing-page'),  # TODO: Maybe use a redirect to Practice list view here.
    path('taggit/', include('taggit_selectize.urls')),
    path('headquarters/', admin.site.urls),
    path('users/', include('users.urls')),
    path('institutes/', include('institutes.urls')),
    path('practices/', include('practices.urls')),
    path('accreditations/', include('accreditation.urls')),
    path('studies/', include('studies.urls')),
    path('events/', include('events.urls')),
    path('todos/', include('todos.urls')),
    path('contactnotes/', include('contactnotes.urls')),
    path('documents/', include('documents.urls')),
    path('processes/', include('processes.urls')),
    path('persons/', include('persons.urls')),
    path('exporter/', include('exporter.urls')),
    path('changelogs/', include('changelogs.urls')),
    path('mail/', include('mail.urls')),
    path('importer/', include('importer.urls')),
    path('practice_importer/', include('practice_importer.urls')),
    path('kbv_importer/', include('kbv_importer.urls')),
    path('feedback/', include('feedback.urls')),
    path('schedule/', include('schedule.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ck_editor_5_upload_file"), #Using own implementation of image upload
    path('api/', include(api_router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

praxisregister_src/apps/practices/models/site.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from practices.types import SiteType
from addresses.models import AddressMixin
from track_changes.models import TrackChangesMixin
from importer.models import ImportableMixin

class Site(TrackChangesMixin, ImportableMixin, AddressMixin, models.Model):
    """
    Site model which encapsulates address and identification number (BSNR) for practices.
    A single practice can have multiple sites.
    """
    practice = models.ForeignKey('practices.Practice', on_delete=models.CASCADE, null=False)
    
    identification_number = models.CharField(
        verbose_name=_('BSNR'),
        max_length=255,
        blank=True,
        default=""
    )
    type = models.CharField(
        verbose_name=_("Site type"),
        max_length=256,
        choices=SiteType.choices,
        default=SiteType.PRIMARY,
        blank=False,
    )
    
    class Meta:
        verbose_name = _("Site")

    def __str__(self):
        return f"{_('Site')}"

praxisregister_src/templates/practices/accreditations/_is_accredited.html
{% load i18n %}

<table class="table table-sm">
    <tbody>
    {# Checking accreditation status and changing css class of this table row accordingly #}
    {% if accreditation.status == "NOT_ACCREDITED" %}
        <tr class="table-danger">
    {% elif accreditation.status == "PENDING" %}
        <tr class="table-info">
    {% elif accreditation.status == "ACCREDITED" %}
        <tr class="table-success">
    {% endif %}
    <th>{% trans 'Accreditation status' %}</th>
    <td>
        <span class="float-end">
            <strong>{{ accreditation.get_status_display }}</strong>
            <a href="{% url 'accreditations:edit' accreditation.id %}">
                <i class="fa fa-edit"></i>
            </a>
        </span>
        <br>
        <span class="float-end">
            {% if accreditation.accredited_at %}
                {{ accreditation.accredited_at }}
                <a href="{% url 'accreditations:edit-accredited-at' accreditation.id %}">
                    <i class="fa fa-edit"></i>
                </a>
            {% endif %}
        </span>
    </td>


    </tr>
    </tbody>
</table>

praxisregister_src/templates/practices/accreditations/checklist.html
{% load i18n %}
{% load accreditation_crit_checkmark %}
{% with criteria=accreditation.accreditation_criteria_dict %}

<h4 class="display-7">
    {{ accreditation }}
    <a href="{% url 'accreditations:edit-checklist' accreditation.id %}" id="id_edit_checklist">
        <i class="fa fa-edit"></i>
    </a>
</h4> 
<div class="row">
    <div class="col">
        <table class="table table-sm mb-0">
            <tbody>
                <tr class="table-secondary border">
                    <th colspan="2">
                        {% trans 'Checklist' %}
                        <span class="float-end">{% trans 'Status' %}</span>
                    </th>
                </tr>

                {% for attribute in accreditation.accreditation_type.accreditationattribute_set.all %}
                {% if attribute.name == "OPERATES_UNTIL" %}
                <tr>
                    <th>{{ attribute|get_display_name }} {{ accreditation.practice_has_to_operate_until }}</th>
                    <td class="align-middle">{{ criteria|get_value:attribute|checkmark }}</td>
                </tr>
                {% elif attribute.name == "PARTICIPATED_IN_EVENTS" %}
                <tr>
                    <th>{{ attribute|get_display_name }}</th>
                    <td>
                        <table class="table table-sm">
                        {% with events=criteria|get_value:attribute %}
                        {% for event, participated in events.items %}
                        <tr> 
                            <th>
                                <a href="{% url 'events:detail' event.id %}">
                                {{ event.title }}
                                </a>
                            </th>
                            <td class="align-middle">{{ participated|checkmark }}</td>
                        </tr>
                        {% endfor %}
                        {% endwith %}
                        </table>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <th>{{ attribute|get_display_name }}</th>
                    <td class="align-middle">{{ criteria|get_value:attribute|checkmark }}</td>
                </tr>
                {% endif %}
                {% empty %}
                <tr>
                    <th>{% trans 'No accreditation attributes have been defined for the checklist yet' %}</th>
                </tr>
                {% endfor %}

{% comment %}                 

                {% if attributes|length_is:"0" %}
                <tr>
                    <th>{% trans 'No accreditation attributes have been defined for the checklist yet' %}</th>
                </tr>
                {% else %}
                    {% for attribute, value in attr_dict.items %}
                        <tr>
                            <th>{{ attribute }}</th>
                            <td>{{ value|checkmark }}</td>
                        </tr>
                    {% endfor %}
                    {% if OPERATES_UNTIL %}
                        {% for label, value in OPERATES_UNTIL.items %}
                        <tr>
                            <th>{{ label }} {{ accreditation.practice_has_to_operate_until }}</th>
                            <td>{{ value|checkmark }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                    {% if PARTICIPATED_IN_EVENTS %}
                        {% for event_label, events_dic in PARTICIPATED_IN_EVENTS.items %}
                            <tr>
                                <th>{{ event_label }}</th>
                                <td>
                                    <table class="table table-sm">
                                    {% for event, participated in events_dic.items %}
                                    <tr> 
                                        <th>{{ event }}</th>
                                        <td>{{ participated|checkmark }}</td>
                                    </tr>
                                    {% endfor %}
                                    </table>
                                </td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                {% endif %} {% endcomment %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col">     
    {% include 'practices/accreditations/_is_accredited.html' %}
    </div>
</div>
{% endwith %}

praxisregister_src/templates/practices/accreditations/detail_checklist.html
{% extends 'practices/practice_base.html' %}
{% load fields_verbose_name %}
{% load accreditation_crit_checkmark %}
{% load i18n %}

{% block page_content %}
    <div class="row">
        <div class="col-sm">
            <h4 class="display-7">
                {% trans 'Accreditation type' %}: {{ accreditation }}
            </h4>
            <p class="display-6 d-inline">
                {% trans 'Accreditation checklist' %}
                <h3 class="d-inline">
                    <a href="{% url 'accreditations:edit-checklist' accreditation.id %}" id="id_edit_checklist">
                        <i class="fa fa-edit"></i>
                    </a>
                </h3>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-sm table-hover">
                <tbody>
                    <tr class="table-secondary border">
                        <th colspan="2">{% trans 'Selected attributes' %}<span class="float-end">{% trans 'Status' %}</span></th>
                    </tr>
                    {% if attributes|length_is:"0" %}
                    <tr>
                        <th>{% trans 'No accreditation attributes have been defined for the checklist yet' %}</th>
                    </tr>
                    {% else %}
                        {% for attribute, value in attr_dict.items %}
                            <tr>
                                <th>{{ attribute }}</th>
                                <td>{{ value|checkmark }}</td>
                            </tr>
                        {% endfor %}
                        {% if OPERATES_UNTIL %}
                            {% for label, value in OPERATES_UNTIL.items %}
                            <tr>
                                <th>{{ label }} {{ accreditation.practice_has_to_operate_until }}</th>
                                <td>{{ value|checkmark }}</td>
                            </tr>
                            {% endfor %}
                        {% endif %}
                        {% if PARTICIPATED_IN_EVENTS %}
                            {% for event_label, events_dic in PARTICIPATED_IN_EVENTS.items %}
                                <tr>
                                    <th>{{ event_label }}</th>
                                    <td>
                                        <table class="table table-sm">
                                        {% for event, participated in events_dic.items %}
                                        <tr> 
                                            <th>{{ event }}</th>
                                            <td>{{ participated|checkmark }}</td>
                                        </tr>
                                        {% endfor %}
                                        </table>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col">     
        {% include 'practices/accreditations/_is_accredited.html' %}
        </div>
    </div>
{% endblock %}

praxisregister_src/templates/practices/accreditations/edit_checklist.html
{% extends 'global/base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block page_content %}
    <h2 id="id_form_header">{{ form.instance }}</h2>
    <form method="post" autocomplete="off">
        {% csrf_token %}
        {% crispy form %}
        {% include 'global/buttons/back_to_previous_site_button.html' %}
        <button type="submit" class="btn btn-primary" id="id_generic_save_button">{% trans 'Save' %} </button>
    </form>
{% endblock %}

praxisregister_src/templates/practices/accreditations/overview.html
{% extends 'practices/practice_base.html' %}
{% load i18n %}

{% block custom_css %}
{% endblock %}

{% block practice-content %}
    <div class="row">
        <div class="col-sm">
            <h3 class="display-6">
                {% trans 'Accreditations' %}
                <a href="{% url 'practices:accreditation-add' practice.id %}" id="id_new_accreditation_button">
                    <i class="fa fa-plus-circle"></i>
                </a>
            </h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm">
            {% for accreditation in practice.accreditations.all %}
                <div class="mb-3">
                {% include "practices/accreditations/checklist.html" %}
                </div>
            {% empty %}
                {% trans 'No accreditations created yet' %}
            {% endfor %}
        </div> 
    </div>


    {% include 'practices/contract/detail.html' %}

{% endblock %}