praxisregister_src/apps/practices/urls.py
from django.urls import path

from accreditation.views import PracticeAccreditationCreate, PracticeAccreditationList
from contactnotes.views import ContactNoteCreate, PracticeContactNotes
from documents.views import DocumentCreate, PracticeDocuments
from events.views.participation_views import EventParticipationCreate, PracticeEventParticipationList
from persons.views import PersonsInPractice, PersonAdd
from processes.views import PracticeProcessList, ProcessParticipationCreate, process_step_select_option
from studies.views.practice_study_overview import PracticeStudyParticipations, StudyParticipationCreate
from todos.views import PracticeToDoCreate, PracticeToDoList, ToDoDelete
from .views.allowed_institutes import AllowedInstitutes, AllowedInstitutesEdit
from .views.practice_base_data import PracticeDetail, PracticeOpeningHoursEdit, \
    PracticeContactEdit, UpdatePracticeBaseData
from .views.contract import *
from .views.it_infrastructure import PracticeITDetail, PracticeITSystemHouseEdit, PracticeITOtherEdit, \
    PracticeITPDMSEdit, PracticeITNotepadEdit
from .views.notepad import PracticeNotepadEdit
from .views.practice import PracticeCreate, Practices, practice_table
from .views.sites import AdditionalSiteEdit, AdditionalSiteDelete, AdditionalSiteCreateView
from .views.practice_structure import *
from .views.research_tandem import TandemAssistantDetail, TandemDoctorDetail
from practices.views.practice_communication import *

app_name = 'practices'

practice_urls = [
    path('', Practices.as_view(), name='list'),
    path('htmx/practice-table/', practice_table, name='practice_table'),
    path('htmx/process-step-selection/', process_step_select_option, name='process-step-selection'),
    path('<int:pk>/', PracticeDetail.as_view(), name='detail'),
    path('new', PracticeCreate.as_view(), name='create'),
    path('<int:pk>/sites/new', AdditionalSiteCreateView.as_view(), name='create-site'),
    path('sites/<int:pk>/edit', AdditionalSiteEdit.as_view(), name='edit-site'),
    path('sites/<int:pk>/delete', AdditionalSiteDelete.as_view(), name='delete-site'),
    path('<int:pk>/notepad/', PracticeNotepadEdit.as_view(), name='edit-notepad'),
    path('<int:pk>/information/edit', UpdatePracticeBaseData.as_view(), name='edit-info'),
    path('<int:pk>/opening-hours/edit', PracticeOpeningHoursEdit.as_view(), name='edit-opening-hours'),
    path('<int:pk>/contact/edit', PracticeContactEdit.as_view(), name='edit-contact'),
]

todo_urls = [
    path('<int:pk>/todos/', PracticeToDoList.as_view(), name='todo-list'),
    path('<int:pk>/todos/new', PracticeToDoCreate.as_view(), name='create-todo'),
    path('<int:pk>/todos/delete', ToDoDelete.as_view(), name='todo-delete'),
]

accreditation_urls = [
    path('<int:pk>/accreditations/new', PracticeAccreditationCreate.as_view(), name='accreditation-add'),
    path('<int:pk>/accreditations/', PracticeAccreditationList.as_view(), name='accreditations'),
]

study_urls = [
    path('<int:pk>/study-participations/', PracticeStudyParticipations.as_view(),
         name='study-participation-list'),
    path('<int:pk>/study-participations/new', StudyParticipationCreate.as_view(),
         name='study-participation-create'),
]

event_urls = [
    path('<int:pk>/event-participations/', PracticeEventParticipationList.as_view(),
         name='event-participation-list'),
    path('<int:pk>/event-participations/new', EventParticipationCreate.as_view(),
         name='event-participation-create'),
]

process_urls = [
    path('<int:pk>/process-participations/', PracticeProcessList.as_view(), name='process-list'),
    path('<int:pk>/process-participations/new', ProcessParticipationCreate.as_view(),
         name='process-participation-create'),
]

contact_notes_urls = [
    path('<int:pk>/contact-notes/', PracticeContactNotes.as_view(), name='contactnote-list'),
    path('<int:pk>/contact-notes/new', ContactNoteCreate.as_view(), name='contactnote-create'),
]

documents_urls = [
    path('<int:pk>/documents/', PracticeDocuments.as_view(), name='document-list'),
    path('<int:pk>/documents/new', DocumentCreate.as_view(), name='document-create'),
]

structure_urls = [
    path('<int:pk>/structure/', PracticeStructureDetail.as_view(),
         name='structure-detail'),
    path('<int:pk>/structure/doctors/edit', PracticeStructureDoctorsEdit.as_view(),
         name='structure-doctors-edit'),
    path('<int:pk>/structure/staff/edit', PracticeStructureStaffEdit.as_view(),
         name='structure-staff-edit'),
    path('structure/assistant-qualifications/<int:pk>/delete',
         PracticeAssistantsAdditionalQualificationDelete.as_view(),
         name='structure-assistant-qualifications-delete'),
    path('<int:pk>/structure/services/edit', PracticeStructureServicesEdit.as_view(),
         name='structure-services-edit'),
    path('structure/engagements/<int:pk>/delete', PracticeEngagementDelete.as_view(),
         name='structure-engagement-delete'),
    path('<int:pk>/structure/general/edit', PracticeStructureGeneralEdit.as_view(),
         name='structure-general-edit'),
    path('structure/dmp-entries/<int:pk>/edit', DiseaseManagementProgramEntryEdit.as_view(),
         name='dmp-entry-edit'),
    path('structure/offers-service/<int:pk>/delete', ServicesPracticeOffersDelete.as_view(), name='practice-offers-delete'),
    path('<int:pk>/structure/treatment-by-age/edit', PracticeTreatmentByAgeGroupPerQuarterEdit.as_view(), name='structure-treatment-by-age-edit'),
    path('structure/treatment-by-age/<int:pk>/delete', PracticeTreatmentByAgeGroupPerQuarterDelete.as_view(), name='structure-treatment-by-age-delete'),
]

it_urls = [
    path('<int:pk>/it/', PracticeITDetail.as_view(), name='it-detail'),
    path('<int:pk>/it/system-house/edit', PracticeITSystemHouseEdit.as_view(), name='it-system-house-edit'),
    path('<int:pk>/it/pdms/edit', PracticeITPDMSEdit.as_view(), name='it-pdms-edit'),
    path('<int:pk>/it/other/edit', PracticeITOtherEdit.as_view(), name='it-other-edit'),
    path('<int:pk>/it/notepad/edit', PracticeITNotepadEdit.as_view(), name='it-notepad-edit'),
]

communication_urls = [
    path('<int:pk>/communication/', PracticeCommunicationView.as_view(), name='communication-detail'),
    path('<int:pk>/communication/spoken-language/edit', PracticeCommunicationEdit.as_view(), name='communication-spoken-language-edit'),
    path('communication/spoken-language/<int:pk>/delete', CommunicationSpokenLanguageDelete.as_view(), name='communication-spoken-language-delete'),
    path('communication/spoken-language/<int:pk>/percentage', CommunicationSpokenLanguagePercentage.as_view(), name='communication-spoken-language-percentage'),
    path('communication/interpreter/<int:pk>/delete', CommunicationInterpreterDelete.as_view(), name='communication-interpreter-delete'),
    path('communication/interpreter/<int:pk>/amount', CommunicationInterpreterAmount.as_view(), name='communication-interpreter-amount'),

    path('<int:pk>/communication/colleagues', PracticeDigitalCommunicationWithColleaguesEdit.as_view(), name='communication-digital-colleagues-edit'),
    path('communication/colleagues/<int:pk>/delete', CommunicationWithColleaguesDelete.as_view(), name='communication-digital-colleagues-delete'),
    
    path('<int:pk>/communication/patients', PracticeDigitalCommunicationWithPatientsEdit.as_view(), name='communication-digital-patients-edit'),
    path('communication/patients/<int:pk>/delete', CommunicationWithPatientsDelete.as_view(), name='communication-digital-patients-delete'),
]

contract_urls = [
    path('<int:pk>/contract/download', download_contract_file, name='contract-download'),
    path('<int:pk>/contract/delete', delete_contract_file, name='contract-delete'),
    path('<int:pk>/contract/edit', ContractEdit.as_view(), name='contract-edit'),
]

persons_urls = [
    path('<int:pk>/persons/', PersonsInPractice.as_view(), name='persons'),
    path('<int:pk>/persons/new', PersonAdd.as_view(), name='person-add'),
]

research_tandem_urls = [
    path('<int:pk>/research-tandem/doctor/', TandemDoctorDetail.as_view(), name='tandem-doctor-detail'),
    path('<int:pk>/research-tandem/assistant/', TandemAssistantDetail.as_view(), name='tandem-assistant-detail'),
]

allowed_institutes_urls = [
    path('<int:pk>/allowed-institutes/', AllowedInstitutes.as_view(), name="allowed-institutes"),
    path('<int:pk>/allowed-institutes/add', AllowedInstitutesEdit.as_view(), name="allowed-institutes-edit")
]

urlpatterns = []
urlpatterns.extend(practice_urls)
urlpatterns.extend(persons_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(it_urls)
urlpatterns.extend(communication_urls)
urlpatterns.extend(structure_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(contact_notes_urls)
urlpatterns.extend(documents_urls)
urlpatterns.extend(event_urls)
urlpatterns.extend(process_urls)
urlpatterns.extend(study_urls)
urlpatterns.extend(todo_urls)
urlpatterns.extend(accreditation_urls)
urlpatterns.extend(research_tandem_urls)
urlpatterns.extend(allowed_institutes_urls)

praxisregister_src/apps/schedule/urls.py
from django.urls import re_path
from django.views.generic.list import ListView

from schedule.feeds import CalendarICalendar, UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView,
    CalendarView,
    CancelOccurrenceView,
    CreateEventView,
    CreateOccurrenceView,
    DeleteEventView,
    EditEventView,
    EditOccurrenceView,
    EventView,
    FullCalendarView,
    OccurrencePreview,
    OccurrenceView,
    api_move_or_resize_by_code,
    api_occurrences,
    api_select_create,
)

urlpatterns = [
    re_path(r"^$", ListView.as_view(model=Calendar), name="calendar_list"),
    re_path(
        r"^calendar/year/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_year.html"),
        name="year_calendar",
        kwargs={"period": Year},
    ),
    re_path(
        r"^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_tri_month.html"),
        name="tri_month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(
            template_name="schedule/calendar_compact_month.html"
        ),
        name="compact_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_month.html"),
        name="month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/week/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_week.html"),
        name="week_calendar",
        kwargs={"period": Week},
    ),
    re_path(
        r"^calendar/daily/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_day.html"),
        name="day_calendar",
        kwargs={"period": Day},
    ),
    re_path(
        r"^calendar/(?P<calendar_slug>[-\w]+)/$",
        CalendarView.as_view(),
        name="calendar_home",
    ),
    re_path(
        r"^fullcalendar/(?P<calendar_slug>[-\w]+)/$",
        FullCalendarView.as_view(),
        name="fullcalendar",
    ),
    # Event Urls
    re_path(
        r"^event/create/(?P<calendar_slug>[-\w]+)/$",
        CreateEventView.as_view(),
        name="calendar_create_event",
    ),
    re_path(
        r"^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$",
        EditEventView.as_view(),
        name="edit_event",
    ),
    re_path(r"^event/(?P<event_id>\d+)/$", EventView.as_view(), name="event"),
    re_path(
        r"^event/delete/(?P<event_id>\d+)/$",
        DeleteEventView.as_view(),
        name="delete_event",
    ),
    # urls for already persisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        OccurrenceView.as_view(),
        name="occurrence",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        EditOccurrenceView.as_view(),
        name="edit_occurrence",
    ),
    # urls for unpersisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        OccurrencePreview.as_view(),
        name="occurrence_by_date",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence_by_date",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CreateOccurrenceView.as_view(),
        name="edit_occurrence_by_date",
    ),
    # feed urls
    re_path(
        r"^feed/calendar/upcoming/(?P<calendar_id>\d+)/$",
        UpcomingEventsFeed(),
        name="upcoming_events_feed",
    ),
    re_path(r"^ical/calendar/(.*)/$", CalendarICalendar(), name="calendar_ical"),
    # api urls
    re_path(r"^api/occurrences", api_occurrences, name="api_occurrences"),
    re_path(
        r"^api/move_or_resize/$", api_move_or_resize_by_code, name="api_move_or_resize"
    ),
    re_path(r"^api/select_create/$", api_select_create, name="api_select_create"),
    re_path(r"^$", ListView.as_view(queryset=Calendar.objects.all()), name="schedule"),
]

praxisregister_src/config/urls.py
from django.urls import path, include
from rest_framework import routers

from practices.views.practice import Practices, PracticeViewSet
from persons.views import PersonViewSet
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from utils.ckeditor5 import upload_file

api_router = routers.DefaultRouter()
api_router.register(r'practices', PracticeViewSet, basename='practices')
api_router.register(r'persons', PersonViewSet, basename='persons')

# Admin stuff
admin.site.site_header = "Praxisregister Admin"
admin.site.site_title = "Praxisregister Admin Portal"

urlpatterns = [
    path('', Practices.as_view(), name='landing-page'),  # TODO: Maybe use a redirect to Practice list view here.
    path('taggit/', include('taggit_selectize.urls')),
    path('headquarters/', admin.site.urls),
    path('users/', include('users.urls')),
    path('institutes/', include('institutes.urls')),
    path('practices/', include('practices.urls')),
    path('accreditations/', include('accreditation.urls')),
    path('studies/', include('studies.urls')),
    path('events/', include('events.urls')),
    path('todos/', include('todos.urls')),
    path('contactnotes/', include('contactnotes.urls')),
    path('documents/', include('documents.urls')),
    path('processes/', include('processes.urls')),
    path('persons/', include('persons.urls')),
    path('exporter/', include('exporter.urls')),
    path('changelogs/', include('changelogs.urls')),
    path('mail/', include('mail.urls')),
    path('importer/', include('importer.urls')),
    path('practice_importer/', include('practice_importer.urls')),
    path('kbv_importer/', include('kbv_importer.urls')),
    path('feedback/', include('feedback.urls')),
    path('schedule/', include('schedule.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ck_editor_5_upload_file"), #Using own implementation of image upload
    path('api/', include(api_router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

praxisregister_src/apps/practices/models/dmp_entry.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DiseaseManagementProgramEntry(models.Model):
    """
    Represents the relation of a practice to specific DMP.
    All possible entries for a practice are created automatically via signals.
    Keeping DMPs as relations allows the admin to add DMP types via admin panel.
    """

    class YesNoPlannedType(models.TextChoices):
        YES = 'YES', _('Yes')
        NO = 'NO', _('No')
        PLANNED = 'Planned', _('Planned')
        UNKNOWN = 'UNKNOWN', _('Unknown')

    practice = models.ForeignKey(
        'practices.Practice',
        related_name="disease_management_programs",
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    type = models.ForeignKey(
        'practices.DiseaseManagementProgramOption',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    status = models.CharField(
        verbose_name=_('Status'),
        max_length=128,
        choices=YesNoPlannedType.choices,
        default=YesNoPlannedType.UNKNOWN,
        blank=False
    )

    @property
    def is_available(self):
        return self.status == self.YesNoPlannedType.YES

    class Meta:
        verbose_name = _("Disease management program")
        unique_together = ('practice', 'type')
        ordering = ['type']

praxisregister_src/templates/practices/practice_structure/additional_functions.html
{% load i18n %}

<table class="table table-sm table-hover">
    <tbody>
        <th>{% trans 'Other function/role of the practice' %}</th>
        {% with practice.engagements.all as engagements %}
            {% if engagements %}
                {% for engagement in engagements %}
                    <tr>
                        <td>{{ engagement.type }}</td>
                        <td class="text-end">
                            <a href="{% url 'practices:structure-engagement-delete' engagement.id %}"
                            class="link-danger">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
            <tr>
                <td><a>{% trans 'No other function/role added yet.' %}</a></td>
                <td></td>
            </tr>
            {% endif %}
        {% endwith %}
    </tbody>
</table>

praxisregister_src/templates/practices/practice_structure/additional_qualifications.html
{% load i18n %}

<table class="table table-sm table-hover">
    <tbody>
        <th>{% trans 'Additional qualifications (staff)' %}</th>
        {% if assistant_qualifications_in_general or assistant_added_qualifications_to_person %}
            {% for qualification in assistant_qualifications_in_general %}
                <tr>
                    <td>{{ qualification.type }}</td>
                    <td class="text-end">
                        <a href="{% url 'practices:structure-assistant-qualifications-delete' qualification.id %}"
                           class="link-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            {% for assistant_qualification in assistant_added_qualifications_to_person %}
                <tr>
                    <td>{{ assistant_qualification.type }}</td>
                    <td class="text-end">     
                        <a href="{% url 'persons:detail' assistant_qualification.assistant_role.person.id %}" class="text-decoration-none">
                            {{ assistant_qualification.assistant_role.person }}                        
                        </a>
                    </td>
                </tr>
            {% endfor %}       
        {% else %}
        <tr>
            <td><a>{% trans 'No qualifications added yet.' %}</a></td>
            <td></td>
        </tr>
        {% endif %}
    </tbody>
</table>

praxisregister_src/templates/practices/practice_structure/dmps.html
{% load i18n %}
{% load fields_verbose_name %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            {% trans 'Disease Management Programs' %}
            <a href="{% url 'practices:dmp-entry-edit' practice.id %}">
                <i class="fa fa-edit"></i>
            </a>
        </h5>
        <table class="table table-sm table-hover">
            <tbody>
            {% for entry in practice.disease_management_programs.all %}
                <tr>
                    <td>{{ entry.type.name }}</td>
                    <td class="text-end">
                        {{ entry.get_status_display }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>

praxisregister_src/templates/practices/practice_structure/doctors.html
{% load i18n %}
{% load fields_verbose_name %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            {% trans 'Doctors' %}
            <a href="{% url 'practices:structure-doctors-edit' practice.id %}">
                <i class="fa fa-edit"></i>
            </a>
        </h5>
        <table class="table table-sm table-hover">
            <tbody>
            <tr>
                <td>{{ practice|verbose:"structure_number_of_doctors_that_are_owners" }}</td>
                <td class="text-end">{{ practice.structure_number_of_doctors_that_are_owners|default:0 }}</td>
            </tr>
            <tr>
                <td>{{ practice|verbose:"structure_number_of_doctors_that_are_employees" }}</td>
                <td class="text-end">{{ practice.structure_number_of_doctors_that_are_employees|default:0 }}</td>
            </tr>
            <tr>
                <td>{{ practice|verbose:"structure_number_of_doctors_that_are_in_training" }}</td>
                <td class="text-end">{{ practice.structure_number_of_doctors_that_are_in_training|default:0 }}</td>
            </tr>
            <tr>
                <td>{{ practice|verbose:"structure_number_of_non_gp_doctors_that_are_in_the_practice" }}</td>
                <td class="text-end">{{ practice.structure_number_of_non_gp_doctors_that_are_in_the_practice|default:0 }}</td>
            </tr>
            <tr style="border-top:double;">
                <th>{% trans 'Doctors in total' %}</th>
                <td class="text-end">{{ practice.total_number_of_doctors }}</td>
            </tr>

            </tbody>
        </table>
        <table class="table table-sm table-hover">
            <tbody>
            <tr>
                <th>{{ practice|verbose:"doctor_has_education_authorization" }}</th>
                <td class="text-end">{{ practice.get_doctor_has_education_authorization_display }}</td>
            </tr>
            <tr>
                <th>{{ practice|verbose:"structure_full_time_equivalent_for_doctors" }}</th>
                <td class="text-end">{{ practice.structure_full_time_equivalent_for_doctors|default:0 }}%</td>
            </tr>
            <tr>
                <th>{{ practice|verbose:"structure_non_gp_doctors_are_working_in_the_practice" }}</th>
                <td class="text-end">{{ practice.get_structure_non_gp_doctors_are_working_in_the_practice_display }}</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

praxisregister_src/templates/practices/practice_structure/general.html
{% load i18n %}
{% load fields_verbose_name %}


<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            {% trans 'General' %}
            <a href="{% url 'practices:structure-general-edit' practice.id %}">
                <i class="fa fa-edit"></i>
            </a>
        </h5>

        <p class="card-text">
        <table class="table table-sm table-hover">

            <tbody>

            <tr>
                <th>{{ practice|verbose:"structure_practice_type" }}</th>
                <td class="text-end">{{ practice.structure_practice_type }}</td>
            </tr>

            <tr>
                <th>{{ practice|verbose:"structure_urbanisation_level" }}</th>
                <td class="text-end">{{ practice.structure_urbanisation_level }}</td>
            </tr>
            <tr>
                <th>{{ practice|verbose:"structure_practice_operating_until" }}</th>
                {% if practice.structure_practice_operating_until %}
                <td class="text-end">{{ practice.structure_practice_operating_until }}</td>
                {% else %}
                <td class="text-end">{% trans 'Unknown' %}</td>
                {% endif %}
            </tr>
            <tr>
                <th>{{ practice|verbose:"structure_full_care_mandate" }}</th>
                <td class="text-end">{{ practice.get_structure_full_care_mandate_display }}</td>
            </tr>
            <tr>
                <th>{{ practice|verbose:"structure_bills_per_quarter" }}</th>
                <td class="text-end">{{ practice.get_structure_bills_per_quarter_display }}</td>
            </tr>

            <tr>
                <th>{{ practice|verbose:"structure_at_least_35_hours_openend" }}</th>
                <td class="text-end">{{ practice.get_structure_at_least_35_hours_openend_display }}</td>
            </tr>
            <tr>
                {% include 'practices/practice_structure/additional_functions.html' %}
            </tr>
            </tbody>
        </table>
        </p>
    </div>
</div>

praxisregister_src/templates/practices/practice_structure/practice_back_to_structure_data.html
{% load i18n %}

<a class=" mt-3 btn btn-primary" href="{% url 'practices:structure-detail' practice_id %}">
    {% trans 'To overview' %}
</a>     

praxisregister_src/templates/practices/practice_structure/services.html
{% load i18n %}
{% load fields_verbose_name %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            {% trans 'Range of services' %}
            <a href="{% url 'practices:structure-services-edit' practice.id %}">
                <i class="fa fa-edit"></i>
            </a>
        </h5>
        <table class="table table-sm table-hover">
            <tbody>
            <tr>
                <th>{{ practice|verbose:"structure_gp_range_of_services" }}</th>
                <td class="text-end">{{ practice.get_structure_gp_range_of_services_display }}</td>
            </tr>
            <tr>
                <th>{{ practice|verbose:"services_home_visits" }}</th>
                <td class="text-end">{{ practice.get_services_home_visits_display }}</td>
            </tr>
            <tr>
                <th>{{ practice|verbose:"services_nursing_home_visits" }}</th>
                <td class="text-end">{{ practice.get_services_nursing_home_visits_display }}</td>
            </tr>
            <tr>
                {% include 'practices/practice_structure/services_offered.html' %}
            </tr>
            </tbody>
        </table>
    </div>
</div>

praxisregister_src/templates/practices/practice_structure/services_offered.html
{% load i18n %}

<table class="table table-sm table-hover">
    <tbody>
        <th>{% trans 'Practices offers the following services' %}</th>
        {% with practice.servicespracticeoffers_set.all as services %}
            {% if services %}
                {% for service in services %}
                    <tr>
                        <td>{{ service.service_name }}</td>
                        <td class="text-end">
                            <a href="{% url 'practices:practice-offers-delete' service.id %}"
                            class="link-danger">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
            <tr>
                <td><a>{% trans 'No service added yet.' %}</a></td>
                <td></td>
            </tr>
            {% endif %}
        {% endwith %}
    </tbody>
</table>

praxisregister_src/templates/practices/practice_structure/treatments_card.html
{% load i18n %}
{% load fields_verbose_name %}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">
            {% trans 'Treatments in detail' %}
            <a href="{% url 'practices:structure-treatment-by-age-edit' practice.id %}">
                <i class="fa fa-edit"></i>
            </a>
        </h5>
        <table class="table table-sm table-hover">
            <tbody>
            <tr>
                {% include 'practices/practice_structure/treatmentsByAgeGroup.html' %}
            </tr>
            </tbody>
        </table>
    </div>
</div>