praxisregister_src/apps/contactnotes/urls.py
from django.urls import path
from contactnotes import views

app_name = 'contactnotes'

urlpatterns = [
    path('<int:pk>/attachments/<int:attachment_id>/download', views.download_contact_note_attachment_file,
         name='attachment-download'),
    path('<int:pk>/edit', views.ContactNoteEdit.as_view(),
         name='edit'),
    path('<int:pk>/delete', views.ContactNoteDelete.as_view(),
         name='contact-note-delete'),
]

praxisregister_src/apps/practices/urls.py
from django.urls import path

from accreditation.views import PracticeAccreditationCreate, PracticeAccreditationList
from contactnotes.views import ContactNoteCreate, PracticeContactNotes
from documents.views import DocumentCreate, PracticeDocuments
from events.views.participation_views import EventParticipationCreate, PracticeEventParticipationList
from persons.views import PersonsInPractice, PersonAdd
from processes.views import PracticeProcessList, ProcessParticipationCreate, process_step_select_option
from studies.views.practice_study_overview import PracticeStudyParticipations, StudyParticipationCreate
from todos.views import PracticeToDoCreate, PracticeToDoList, ToDoDelete
from .views.allowed_institutes import AllowedInstitutes, AllowedInstitutesEdit
from .views.practice_base_data import PracticeDetail, PracticeOpeningHoursEdit, \
    PracticeContactEdit, UpdatePracticeBaseData
from .views.contract import *
from .views.it_infrastructure import PracticeITDetail, PracticeITSystemHouseEdit, PracticeITOtherEdit, \
    PracticeITPDMSEdit, PracticeITNotepadEdit
from .views.notepad import PracticeNotepadEdit
from .views.practice import PracticeCreate, Practices, practice_table
from .views.sites import AdditionalSiteEdit, AdditionalSiteDelete, AdditionalSiteCreateView
from .views.practice_structure import *
from .views.research_tandem import TandemAssistantDetail, TandemDoctorDetail
from practices.views.practice_communication import *

app_name = 'practices'

practice_urls = [
    path('', Practices.as_view(), name='list'),
    path('htmx/practice-table/', practice_table, name='practice_table'),
    path('htmx/process-step-selection/', process_step_select_option, name='process-step-selection'),
    path('<int:pk>/', PracticeDetail.as_view(), name='detail'),
    path('new', PracticeCreate.as_view(), name='create'),
    path('<int:pk>/sites/new', AdditionalSiteCreateView.as_view(), name='create-site'),
    path('sites/<int:pk>/edit', AdditionalSiteEdit.as_view(), name='edit-site'),
    path('sites/<int:pk>/delete', AdditionalSiteDelete.as_view(), name='delete-site'),
    path('<int:pk>/notepad/', PracticeNotepadEdit.as_view(), name='edit-notepad'),
    path('<int:pk>/information/edit', UpdatePracticeBaseData.as_view(), name='edit-info'),
    path('<int:pk>/opening-hours/edit', PracticeOpeningHoursEdit.as_view(), name='edit-opening-hours'),
    path('<int:pk>/contact/edit', PracticeContactEdit.as_view(), name='edit-contact'),
]

todo_urls = [
    path('<int:pk>/todos/', PracticeToDoList.as_view(), name='todo-list'),
    path('<int:pk>/todos/new', PracticeToDoCreate.as_view(), name='create-todo'),
    path('<int:pk>/todos/delete', ToDoDelete.as_view(), name='todo-delete'),
]

accreditation_urls = [
    path('<int:pk>/accreditations/new', PracticeAccreditationCreate.as_view(), name='accreditation-add'),
    path('<int:pk>/accreditations/', PracticeAccreditationList.as_view(), name='accreditations'),
]

study_urls = [
    path('<int:pk>/study-participations/', PracticeStudyParticipations.as_view(),
         name='study-participation-list'),
    path('<int:pk>/study-participations/new', StudyParticipationCreate.as_view(),
         name='study-participation-create'),
]

event_urls = [
    path('<int:pk>/event-participations/', PracticeEventParticipationList.as_view(),
         name='event-participation-list'),
    path('<int:pk>/event-participations/new', EventParticipationCreate.as_view(),
         name='event-participation-create'),
]

process_urls = [
    path('<int:pk>/process-participations/', PracticeProcessList.as_view(), name='process-list'),
    path('<int:pk>/process-participations/new', ProcessParticipationCreate.as_view(),
         name='process-participation-create'),
]

contact_notes_urls = [
    path('<int:pk>/contact-notes/', PracticeContactNotes.as_view(), name='contactnote-list'),
    path('<int:pk>/contact-notes/new', ContactNoteCreate.as_view(), name='contactnote-create'),
]

documents_urls = [
    path('<int:pk>/documents/', PracticeDocuments.as_view(), name='document-list'),
    path('<int:pk>/documents/new', DocumentCreate.as_view(), name='document-create'),
]

structure_urls = [
    path('<int:pk>/structure/', PracticeStructureDetail.as_view(),
         name='structure-detail'),
    path('<int:pk>/structure/doctors/edit', PracticeStructureDoctorsEdit.as_view(),
         name='structure-doctors-edit'),
    path('<int:pk>/structure/staff/edit', PracticeStructureStaffEdit.as_view(),
         name='structure-staff-edit'),
    path('structure/assistant-qualifications/<int:pk>/delete',
         PracticeAssistantsAdditionalQualificationDelete.as_view(),
         name='structure-assistant-qualifications-delete'),
    path('<int:pk>/structure/services/edit', PracticeStructureServicesEdit.as_view(),
         name='structure-services-edit'),
    path('structure/engagements/<int:pk>/delete', PracticeEngagementDelete.as_view(),
         name='structure-engagement-delete'),
    path('<int:pk>/structure/general/edit', PracticeStructureGeneralEdit.as_view(),
         name='structure-general-edit'),
    path('structure/dmp-entries/<int:pk>/edit', DiseaseManagementProgramEntryEdit.as_view(),
         name='dmp-entry-edit'),
    path('structure/offers-service/<int:pk>/delete', ServicesPracticeOffersDelete.as_view(), name='practice-offers-delete'),
    path('<int:pk>/structure/treatment-by-age/edit', PracticeTreatmentByAgeGroupPerQuarterEdit.as_view(), name='structure-treatment-by-age-edit'),
    path('structure/treatment-by-age/<int:pk>/delete', PracticeTreatmentByAgeGroupPerQuarterDelete.as_view(), name='structure-treatment-by-age-delete'),
]

it_urls = [
    path('<int:pk>/it/', PracticeITDetail.as_view(), name='it-detail'),
    path('<int:pk>/it/system-house/edit', PracticeITSystemHouseEdit.as_view(), name='it-system-house-edit'),
    path('<int:pk>/it/pdms/edit', PracticeITPDMSEdit.as_view(), name='it-pdms-edit'),
    path('<int:pk>/it/other/edit', PracticeITOtherEdit.as_view(), name='it-other-edit'),
    path('<int:pk>/it/notepad/edit', PracticeITNotepadEdit.as_view(), name='it-notepad-edit'),
]

communication_urls = [
    path('<int:pk>/communication/', PracticeCommunicationView.as_view(), name='communication-detail'),
    path('<int:pk>/communication/spoken-language/edit', PracticeCommunicationEdit.as_view(), name='communication-spoken-language-edit'),
    path('communication/spoken-language/<int:pk>/delete', CommunicationSpokenLanguageDelete.as_view(), name='communication-spoken-language-delete'),
    path('communication/spoken-language/<int:pk>/percentage', CommunicationSpokenLanguagePercentage.as_view(), name='communication-spoken-language-percentage'),
    path('communication/interpreter/<int:pk>/delete', CommunicationInterpreterDelete.as_view(), name='communication-interpreter-delete'),
    path('communication/interpreter/<int:pk>/amount', CommunicationInterpreterAmount.as_view(), name='communication-interpreter-amount'),

    path('<int:pk>/communication/colleagues', PracticeDigitalCommunicationWithColleaguesEdit.as_view(), name='communication-digital-colleagues-edit'),
    path('communication/colleagues/<int:pk>/delete', CommunicationWithColleaguesDelete.as_view(), name='communication-digital-colleagues-delete'),
    
    path('<int:pk>/communication/patients', PracticeDigitalCommunicationWithPatientsEdit.as_view(), name='communication-digital-patients-edit'),
    path('communication/patients/<int:pk>/delete', CommunicationWithPatientsDelete.as_view(), name='communication-digital-patients-delete'),
]

contract_urls = [
    path('<int:pk>/contract/download', download_contract_file, name='contract-download'),
    path('<int:pk>/contract/delete', delete_contract_file, name='contract-delete'),
    path('<int:pk>/contract/edit', ContractEdit.as_view(), name='contract-edit'),
]

persons_urls = [
    path('<int:pk>/persons/', PersonsInPractice.as_view(), name='persons'),
    path('<int:pk>/persons/new', PersonAdd.as_view(), name='person-add'),
]

research_tandem_urls = [
    path('<int:pk>/research-tandem/doctor/', TandemDoctorDetail.as_view(), name='tandem-doctor-detail'),
    path('<int:pk>/research-tandem/assistant/', TandemAssistantDetail.as_view(), name='tandem-assistant-detail'),
]

allowed_institutes_urls = [
    path('<int:pk>/allowed-institutes/', AllowedInstitutes.as_view(), name="allowed-institutes"),
    path('<int:pk>/allowed-institutes/add', AllowedInstitutesEdit.as_view(), name="allowed-institutes-edit")
]

urlpatterns = []
urlpatterns.extend(practice_urls)
urlpatterns.extend(persons_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(it_urls)
urlpatterns.extend(communication_urls)
urlpatterns.extend(structure_urls)
urlpatterns.extend(contract_urls)
urlpatterns.extend(contact_notes_urls)
urlpatterns.extend(documents_urls)
urlpatterns.extend(event_urls)
urlpatterns.extend(process_urls)
urlpatterns.extend(study_urls)
urlpatterns.extend(todo_urls)
urlpatterns.extend(accreditation_urls)
urlpatterns.extend(research_tandem_urls)
urlpatterns.extend(allowed_institutes_urls)

praxisregister_src/apps/schedule/urls.py
from django.urls import re_path
from django.views.generic.list import ListView

from schedule.feeds import CalendarICalendar, UpcomingEventsFeed
from schedule.models import Calendar
from schedule.periods import Day, Month, Week, Year
from schedule.views import (
    CalendarByPeriodsView,
    CalendarView,
    CancelOccurrenceView,
    CreateEventView,
    CreateOccurrenceView,
    DeleteEventView,
    EditEventView,
    EditOccurrenceView,
    EventView,
    FullCalendarView,
    OccurrencePreview,
    OccurrenceView,
    api_move_or_resize_by_code,
    api_occurrences,
    api_select_create,
)

urlpatterns = [
    re_path(r"^$", ListView.as_view(model=Calendar), name="calendar_list"),
    re_path(
        r"^calendar/year/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_year.html"),
        name="year_calendar",
        kwargs={"period": Year},
    ),
    re_path(
        r"^calendar/tri_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_tri_month.html"),
        name="tri_month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/compact_month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(
            template_name="schedule/calendar_compact_month.html"
        ),
        name="compact_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/month/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_month.html"),
        name="month_calendar",
        kwargs={"period": Month},
    ),
    re_path(
        r"^calendar/week/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_week.html"),
        name="week_calendar",
        kwargs={"period": Week},
    ),
    re_path(
        r"^calendar/daily/(?P<calendar_slug>[-\w]+)/$",
        CalendarByPeriodsView.as_view(template_name="schedule/calendar_day.html"),
        name="day_calendar",
        kwargs={"period": Day},
    ),
    re_path(
        r"^calendar/(?P<calendar_slug>[-\w]+)/$",
        CalendarView.as_view(),
        name="calendar_home",
    ),
    re_path(
        r"^fullcalendar/(?P<calendar_slug>[-\w]+)/$",
        FullCalendarView.as_view(),
        name="fullcalendar",
    ),
    # Event Urls
    re_path(
        r"^event/create/(?P<calendar_slug>[-\w]+)/$",
        CreateEventView.as_view(),
        name="calendar_create_event",
    ),
    re_path(
        r"^event/edit/(?P<calendar_slug>[-\w]+)/(?P<event_id>\d+)/$",
        EditEventView.as_view(),
        name="edit_event",
    ),
    re_path(r"^event/(?P<event_id>\d+)/$", EventView.as_view(), name="event"),
    re_path(
        r"^event/delete/(?P<event_id>\d+)/$",
        DeleteEventView.as_view(),
        name="delete_event",
    ),
    # urls for already persisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        OccurrenceView.as_view(),
        name="occurrence",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<occurrence_id>\d+)/$",
        EditOccurrenceView.as_view(),
        name="edit_occurrence",
    ),
    # urls for unpersisted occurrences
    re_path(
        r"^occurrence/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        OccurrencePreview.as_view(),
        name="occurrence_by_date",
    ),
    re_path(
        r"^occurrence/cancel/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CancelOccurrenceView.as_view(),
        name="cancel_occurrence_by_date",
    ),
    re_path(
        r"^occurrence/edit/(?P<event_id>\d+)/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/(?P<hour>\d+)/(?P<minute>\d+)/(?P<second>\d+)/$",
        CreateOccurrenceView.as_view(),
        name="edit_occurrence_by_date",
    ),
    # feed urls
    re_path(
        r"^feed/calendar/upcoming/(?P<calendar_id>\d+)/$",
        UpcomingEventsFeed(),
        name="upcoming_events_feed",
    ),
    re_path(r"^ical/calendar/(.*)/$", CalendarICalendar(), name="calendar_ical"),
    # api urls
    re_path(r"^api/occurrences", api_occurrences, name="api_occurrences"),
    re_path(
        r"^api/move_or_resize/$", api_move_or_resize_by_code, name="api_move_or_resize"
    ),
    re_path(r"^api/select_create/$", api_select_create, name="api_select_create"),
    re_path(r"^$", ListView.as_view(queryset=Calendar.objects.all()), name="schedule"),
]

praxisregister_src/config/urls.py
from django.urls import path, include
from rest_framework import routers

from practices.views.practice import Practices, PracticeViewSet
from persons.views import PersonViewSet
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from utils.ckeditor5 import upload_file

api_router = routers.DefaultRouter()
api_router.register(r'practices', PracticeViewSet, basename='practices')
api_router.register(r'persons', PersonViewSet, basename='persons')

# Admin stuff
admin.site.site_header = "Praxisregister Admin"
admin.site.site_title = "Praxisregister Admin Portal"

urlpatterns = [
    path('', Practices.as_view(), name='landing-page'),  # TODO: Maybe use a redirect to Practice list view here.
    path('taggit/', include('taggit_selectize.urls')),
    path('headquarters/', admin.site.urls),
    path('users/', include('users.urls')),
    path('institutes/', include('institutes.urls')),
    path('practices/', include('practices.urls')),
    path('accreditations/', include('accreditation.urls')),
    path('studies/', include('studies.urls')),
    path('events/', include('events.urls')),
    path('todos/', include('todos.urls')),
    path('contactnotes/', include('contactnotes.urls')),
    path('documents/', include('documents.urls')),
    path('processes/', include('processes.urls')),
    path('persons/', include('persons.urls')),
    path('exporter/', include('exporter.urls')),
    path('changelogs/', include('changelogs.urls')),
    path('mail/', include('mail.urls')),
    path('importer/', include('importer.urls')),
    path('practice_importer/', include('practice_importer.urls')),
    path('kbv_importer/', include('kbv_importer.urls')),
    path('feedback/', include('feedback.urls')),
    path('schedule/', include('schedule.urls')),
    path("ckeditor5/image_upload/", upload_file, name="ck_editor_5_upload_file"), #Using own implementation of image upload
    path('api/', include(api_router.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

praxisregister_src/apps/practices/models/options.py
from django.db import models


class PracticeEngagementOption(models.Model):
    """
    Represents options for PracticeEngagement.type
    """
    name = models.CharField(max_length=512, blank=False, default="", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class DiseaseManagementProgramOption(models.Model):
    """
    Represents options for DiseaseManagementProgramEntry.type
    """
    name = models.CharField(max_length=256, blank=False, default="", unique=True)
    sort_index = models.PositiveSmallIntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['sort_index']


class PDMSSoftwareOption(models.Model):
    """
    Represents a single option for PDMS choices
    """
    name = models.CharField(max_length=256, blank=False, default="", unique=True)

    def __str__(self):
        return self.name


class OperatingSystemOption(models.Model):
    """
    Represents OS options for the many-to-many field on the practice/IT-infrastructure model.
    """
    name = models.CharField(max_length=256, blank=False, default="", unique=True)

    def __str__(self):
        return self.name

praxisregister_src/templates/practices/contactnotes/practice_contactnote_list.html
{% extends 'practices/practice_base.html' %}
{% load i18n %}
{% load crispy_forms_filters %}
{% block custom_css %}
    {% include 'global/snippets/custom_table_css.html' %}
{% endblock %}

{% block practice-content %}

    <div class="row">
        <div class="col-sm mb-3">
            <h3 class="display-6">{% trans 'Contact notes' %}
                <a href="{% url 'practices:contactnote-create' practice.id %}">
                    <i class="fa fa-plus-circle"></i>
                </a>
            </h3>
        </div>
        <div class="col-sm mb-3 mt-2 text-end">
            <form method="get" autocomplete="off" id="contact_note_filter_form">
                {% trans 'Filter notes by tag:' %} {{ filter.form.tags }}
                <input class="btn btn-primary" type="submit" value="{% trans 'Apply' %}"/>
            </form>
        </div>
    </div>

    {% for contactnote in page_obj %}
        <table class="table table-sm table-borderless">
            <tbody>
            <tr class="table-primary">
                <td>
                    <span>
                        {% trans 'Created at' %} {{ contactnote.created_at }} {% trans 'by' %} {{ contactnote.author }}
                    </span>
                    <span class="float-end">
                            <a href="{% url 'contactnotes:edit' contactnote.id %}">
                                <i class="fa fa-edit"></i> {% trans 'Edit' %}
                            </a>
                            <a href="{% url 'contactnotes:contact-note-delete' contactnote.id %}"
                            class="btn btn-sm btn-outline-danger">
                              <i class="fa fa-trash"></i> {% trans 'Delete' %}
                            </a>
                    </span>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="row">
                        <div class="col-sm-2">
                            <dt>{% trans 'Correspondence' %}</dt>
                            <dd>
                                {% if contactnote.contact_person %}
                                    {% trans 'with' %} {{ contactnote.contact_person }}
                                {% endif %}
                                {% trans 'via' %} {{ contactnote.get_contact_medium_display|capfirst }}
                            </dd>
                            {% if contactnote.contact_date %}
                                <dt>{% trans 'Contact Time' %}</dt>
                                <dd>
                                    {{ contactnote.contact_date }}{% if contactnote.contact_time %}:
                                        {{ contactnote.contact_time|time }}{% endif %}
                                </dd>
                            {% endif %}
                            <dt>{% trans 'Direction' %}</dt>
                            <dd>
                                {{ contactnote.get_direction_display|capfirst }}
                            </dd>
                            <dt>{% trans 'Tags' %}</dt>
                            <dd>

                                {% for tag in contactnote.tags.all %}
                                    <span class="badge bg-primary">{{ tag.slug }}</span>
                                {% endfor %}

                            </dd>
                        </div>
                        <div class="col-sm">
                            <dt>{% trans 'Protocol' %}</dt>
                            <dd>
                                {{ contactnote.note|linebreaksbr }}
                            </dd>
                        </div>
                        {% if contactnote.attachments_with_id_and_short_name %}
                            <div class="col-sm">
                                <dt>{% trans 'Attachments' %}</dt>
                                <ul>
                                    {% for attachment_id, attachment, short_name in contactnote.attachments_with_id_and_short_name %}
                                        <li>
                                            <a href="{% url 'contactnotes:attachment-download' contactnote.id attachment_id %}">
                                                {{ short_name }}
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </td>

            </tr>


            </tbody>

        </table>
    {% endfor %}
    {% include 'global/snippets/pagination.html' %}

{% endblock %}


{% block custom_script %}
    <script>
        //hack to make filter case insensitive
        //TODO: there must be a much better way doing this in the view / on server side
        let tag_filter_input = "#id_tags"
        let filter_form = "#contact_note_filter_form"

        // submit logic
        $(filter_form).submit(function () {
            let lowercase_input = $(tag_filter_input).val().toLowerCase();
            $(tag_filter_input).val(lowercase_input);
        });
    </script>

{% endblock %}